Search test files rather than declaring them in a variable.

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -126,101 +126,100 @@ COOKIES=$(mktemp --suffix=.cookies)
 # </preparation>
 ###############################################################################
 
-if [ $# -gt 0 ]; then
-	tests="$@"
-else
-	tests='
-betriebsrichtung
-# failures
-register_failure
-activate_failure
-login_failure
-changepasswd_failure
-csrf_token
-# success
-register_spam
-changepasswd
-changepasswd_lang_de
-profile
-profile_lang_de
-schedule
-watchlist
-airportcity
-getflights
-'
+readarray -t testsuites < <(
+	if [ $# -eq 0 ]; then
+		find "$PRJDIR/tests/" -maxdepth 1 -type f -name "test_*.sh" -printf "%f\n" |
+		sort -n |
+		sed -r 's/test_(.+)\.sh$/\1/g'
+	else
+		# Get test base name and check for the presence of the testsuite file
+		for file
+		do
+			[[ $file ]] || continue
+
+			testsuite=$(basename "$file" ".sh")
+			testsuite="${testsuite#test_}"
+
+			if [ -r "$PRJDIR/tests/test_$testsuite.sh" ]; then
+				echo "$testsuite"
+			else
+				echo -e "\033[31mCannot find 'test_$testsuite'.\033[m" >&2
+				exit 1
+			fi
+		done
+	fi
+)
+
+if [[ ${#testsuites[@]} -eq 0 ]]; then
+	echo -e "\033[31mNo testsuites specified or no files found.\033[m" >&2
+	exit 1
 fi
 
 status=0
 
-while read testsuite
+for testsuite in "${testsuites[@]}"
 do
-	if [ -n "$testsuite" ]; then
-		if echo "$testsuite" | grep -vq '^[[:space:]]*#'; then
-			echo -e "\033[36m$testsuite\033[m"
+	echo -e "\033[36m$testsuite\033[m"
 
-			export expect="$SCRIPTDIR/expect/$testsuite"
-			export results="$SCRIPTDIR/results/$testsuite"
+	export expect="$SCRIPTDIR/expect/$testsuite"
+	export results="$SCRIPTDIR/results/$testsuite"
 
-			script="test_$testsuite"
+	rm -rf "$results"
+	mkdir -p "$results"
 
-			rm -rf "$results"
-			mkdir -p "$results"
+	mailtodisk --remove '*'
 
-			mailtodisk --remove '*'
+	export mailfile=$(readlink -m "$results/mail.txt")
+	unset csrftoken
 
-			export mailfile=$(readlink -m "$results/mail.txt")
-			unset csrftoken
+	rm -f "$COOKIES"
 
-			rm -f "$COOKIES"
+	# drop/re-create database
+	initdb
 
-			# drop/re-create database
-			initdb
+	eval "$(cat "$PRJDIR/tests/test_$testsuite.sh")"
 
-			eval "$(cat "$SCRIPTDIR/$script.sh")"
-
-			if [ -e "$results/mail.txt" ]; then
-				# See user.php:
-				#     http://www.outlookfaq.net/index.php?action=artikel&cat=6&id=84&artlang=de
-				iconv -f iso-8859-1 -t utf-8 "$results/mail.txt" |
-				sed -r "
-					s#::1#<localhost>#g
-					s#127.0.0.1#<localhost>#g
-					s#(X-Mailer: PHP/).*\$#\1*#g
-					s#(https?://[^/]+/).*/([^/?]+\?.*)#\1/\2#g
-					s#((Mon|Tues|Wednes|Thurs|Fri|Satur|Sun)day), [0-9]+/[0-9]+/[0-9]+#Day, 00/00/00#g
-					s/((Mon|Diens|Donners|Frei|Sams|Sonn)tag|Mittwoch), [0-9]+\. (Januar|Februar|März|April|Mai|Ju[nl]i|August|(Sept|Nov|Dez)ember|Oktober) [0-9]+/Tag, 00. Monat 0000/g
-					s/^(Date:[ \t]+).+\$/\1Day, 0 Month 0000 00:00:00 +0000/g
-					s/[0-9]{4}-[0-9]{2}-[0-9]{2}([ T])[0-9]{2}:[0-9]{2}:[0-9]{2}/0000-00-00\100:00:00/g
-					s/00\+[0-9]{4}/00+0000/g
-					s/token=[0-9a-f]+/token=***/g
-					s/token='[0-9a-f.]+'/token='***'/g
-					s/\(code [0-9]+\)/(code ***)/g
-					/(Activation|Password) token is:/ { N; s/\n.+\$/\n***/g }
-					/Das (Aktivierungs-)?Token( dafür)? ist:/ { N; s/\n.+\$/\n***/g }
-					s/^.*\.php\([0-9]+\): *//g
-				" > "$results/mail-utf-8.txt" &&
-				mv "$results/mail-utf-8.txt" "$results/mail.txt"
-			fi
-
-			if [[ ${copy_scripts:-} ]]; then
-				# Copy referenced scripts to properly view results
-				cp -al "$PRJDIR/css" "$PRJDIR/img" "$PRJDIR/script" "$results"
-			fi
-
-			if ! diff=$(
-				diff "$expect" "$results" \
-					--brief \
-					--recursive \
-					--exclude=css \
-					--exclude=img \
-					--exclude=script
-				)
-			then
-				echo -e "\033[31m└──> FAILED\033[m"
-				status=1
-			fi
-		fi
+	if [ -e "$results/mail.txt" ]; then
+		# See user.php:
+		#     http://www.outlookfaq.net/index.php?action=artikel&cat=6&id=84&artlang=de
+		iconv -f iso-8859-1 -t utf-8 "$results/mail.txt" |
+		sed -r "
+			s#::1#<localhost>#g
+			s#127.0.0.1#<localhost>#g
+			s#(X-Mailer: PHP/).*\$#\1*#g
+			s#(https?://[^/]+/).*/([^/?]+\?.*)#\1/\2#g
+			s#((Mon|Tues|Wednes|Thurs|Fri|Satur|Sun)day), [0-9]+/[0-9]+/[0-9]+#Day, 00/00/00#g
+			s/((Mon|Diens|Donners|Frei|Sams|Sonn)tag|Mittwoch), [0-9]+\. (Januar|Februar|März|April|Mai|Ju[nl]i|August|(Sept|Nov|Dez)ember|Oktober) [0-9]+/Tag, 00. Monat 0000/g
+			s/^(Date:[ \t]+).+\$/\1Day, 0 Month 0000 00:00:00 +0000/g
+			s/[0-9]{4}-[0-9]{2}-[0-9]{2}([ T])[0-9]{2}:[0-9]{2}:[0-9]{2}/0000-00-00\100:00:00/g
+			s/00\+[0-9]{4}/00+0000/g
+			s/token=[0-9a-f]+/token=***/g
+			s/token='[0-9a-f.]+'/token='***'/g
+			s/\(code [0-9]+\)/(code ***)/g
+			/(Activation|Password) token is:/ { N; s/\n.+\$/\n***/g }
+			/Das (Aktivierungs-)?Token( dafür)? ist:/ { N; s/\n.+\$/\n***/g }
+			s/^.*\.php\([0-9]+\): *//g
+		" > "$results/mail-utf-8.txt" &&
+		mv "$results/mail-utf-8.txt" "$results/mail.txt"
 	fi
-done <<< "$tests"
+
+	if [[ ${copy_scripts:-} ]]; then
+		# Copy referenced scripts to properly view results
+		cp -al "$PRJDIR/css" "$PRJDIR/img" "$PRJDIR/script" "$results"
+	fi
+
+	if ! diff=$(
+		diff "$expect" "$results" \
+			--brief \
+			--recursive \
+			--exclude=css \
+			--exclude=img \
+			--exclude=script
+		)
+	then
+		echo -e "\033[31m└──> FAILED\033[m"
+		status=1
+	fi
+done
 
 exit $status
